### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by thebigsmileXD** [QuiverlyRivalry/WarpUI#1]
https://github.com/QuiverlyRivalry/WarpUI/blob/master/src/WarpUI/buttons.php#L5 - missing `;` in the end

no class inside the file

no plugin.yml

no .poggit.yml (needed for virion import)

**Comment by QuiverlyRivalry** [comment]
Im using JoeJoes one tho..

**Comment by thebigsmileXD** [comment]
Code issue have nothing do do with what you are using. The missing `;` as example

**Comment by QuiverlyRivalry** [comment]
Ohhh thanks

**Comment by David-AI** [comment]
An Unknown error occurred

**Comment by QuiverlyRivalry** [comment]
Ill fix this

**Comment by QuiverlyRivalry** [comment]
where would d ; go
